[server]
enableStaticServing = true

[theme]
font="Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
base="light"
primaryColor="#2EBDEE"

[theme.sidebar]
backgroundColor="#0A2A59"
secondaryBackgroundColor="#2EBDEE"
primaryColor="#1988AE"

