[server]
enableStaticServing = true

[theme]
font="inter"
codeFont="inter"
base="dark"
primaryColor="#2EBDEE"

[theme.sidebar]
primaryColor="#1988AE"

[[theme.fontFaces]]
family="inter"
url="mms_image_generat/static/Inter-VariableFont_wdth,wght.ttf"
style="normal"
